
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COM DOT EQUALS ID INT LBRACE LEQ LPAREN MAYOR MENOR NUM OUT PLUS PRINTLN RBRACE RPAREN SEMICOLON STRING SYSTEM WHILEwhile_loop : INT ID EQUALS NUM SEMICOLON WHILE LPAREN ID LEQ NUM RPAREN LBRACE SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON ID PLUS PLUS SEMICOLON RBRACE'
    
_lr_action_items = {'INT':([0,],[2,]),'$end':([1,27,],[0,-1,]),'ID':([2,8,19,22,],[3,9,20,23,]),'EQUALS':([3,],[4,]),'NUM':([4,10,],[5,11,]),'SEMICOLON':([5,21,25,],[6,22,26,]),'WHILE':([6,],[7,]),'LPAREN':([7,18,],[8,19,]),'LEQ':([9,],[10,]),'RPAREN':([11,20,],[12,21,]),'LBRACE':([12,],[13,]),'SYSTEM':([13,],[14,]),'DOT':([14,16,],[15,17,]),'OUT':([15,],[16,]),'PRINTLN':([17,],[18,]),'PLUS':([23,24,],[24,25,]),'RBRACE':([26,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'while_loop':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> while_loop","S'",1,None,None,None),
  ('while_loop -> INT ID EQUALS NUM SEMICOLON WHILE LPAREN ID LEQ NUM RPAREN LBRACE SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON ID PLUS PLUS SEMICOLON RBRACE','while_loop',26,'p_while_loop','sintactico.py',88),
]
